apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: prod
  template:
    metadata:
      name: 'myapp-{{env}}'
    spec:
      project: myapp
      source:
        repoURL: https://github.com/mohamed-55-iti/argocd.git
        targetRevision: main
        path: 'apps/myapp/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'myapp-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
