apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-prod
resources:
  - ../../base
images:
  - name: mohamed11755/cicd-app
    newTag: "5-d510030"
replicas:
  - name: myapp
    count: 3
patches:
  - target:
      kind: Service
      name: myapp
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30092
